# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 949ff441970988dfdac112eaa5a3d7fefa80ad2144d1db0f26294c3e28340c049bc7afb6415161dae1a704abdb35cd0d1647507e3cc29c650a4d79c4f6d65eb9

default: &default
  title: SimpleBlog
  title_html: <b>Simple</b>Blog
  host: test.com

development:
  <<: *default
  admin:
    username: admin
    password: admin

test:
  <<: *default
  admin:
    username: admin
    password: admin

production:
  <<: *default
  admin:
    username: admin
    password: admin

  analytics_js: >
    <script>
    </script>
